<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\OnlineCoursesPlatform.Application\OnlineCoursesPlatform.Application.csproj" />
    <ProjectReference Include="..\OnlineCoursesPlatform.Domain\OnlineCoursesPlatform.Domain.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
